name: Test and Push to Docker Hub

on:
  push:
    paths-ignore:
      - '**.rst'
    branches:
      - master

jobs:

  build-gpu:

    runs-on: nvidia-gpu

    steps:
      - uses: actions/checkout@v2
      - name: Build and push GPU image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ucberkeleyseti/hyperseti_gpu
          tags: latest
